### ISSUE TITLE
POST-Route to MongoDB

### ISSUE THREAD

**Issue by SvLowman** [SvLowman/tagtrace#13]
## User Story

I want an POST-Route to MongoDB so that I can (via input field) add imageEntries and tags to my database.

## Notes, Links, Further Descriptions

...

## ToDos

- [x] Create a route for posting imagesEntries
- [x] Create a route for posting new tags
- [x] Build a form for posting tags
