### ISSUE TITLE
Install media query, expecially for landscape-orientated screens

### ISSUE THREAD

**Issue by SvLowman** [SvLowman/tagtrace#45]
## User Story

I want media queries, so that the design changes, especially when I want to use the application on a desktop and not on a phone.

## Notes, Links, Further Descriptions

...

## ToDos

- [x] Research how media queries work
- [x] Use media queries for tagging page
- [x] Use media queries for gallery page
